services:
  risk-mock:
    build:
      context: ./mocks
      dockerfile: Dockerfile
      args:
        SERVICE: risk
    environment:
      PORT: 8080
    ports:
      - "8081:8080"

  notify-mock:
    build:
      context: ./mocks
      dockerfile: Dockerfile
      args:
        SERVICE: notify
    environment:
      PORT: 8080
    ports:
      - "8082:8080"
